import js from '@eslint/js'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'release/**',
      '.worktrees/**',
      'electron/**',
      'deploy/**',
      'scripts/**',
      'e2e/**',
      'vite.config.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      'no-undef': 'off',
      'no-unused-vars': 'off',
      'no-empty': 'off',
      'no-constant-condition': 'off',
      'prefer-const': 'off',
      'no-useless-escape': 'off',
      'no-control-regex': 'off',
      'no-debugger': 'error',
      'no-eval': 'error',
      'no-useless-assignment': 'off',
      'no-constant-binary-expression': 'off',
      'preserve-caught-error': 'off',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
    },
  },
  {
    files: [
      'src/lib/taskBootstrap.ts',
      'src/lib/taskBootstrap.test.ts',
      'src/lib/taskImageReferences.ts',
      'src/lib/taskImageReferences.test.ts',
      'src/lib/taskRecovery.ts',
      'src/lib/taskRecovery.test.ts',
      'src/lib/taskRecoveryManager.ts',
      'src/lib/taskRecoveryManager.test.ts',
      'src/lib/imageReferenceCleanup.ts',
      'src/lib/imageReferenceCleanup.test.ts',
      'src/lib/taskDeletionManager.ts',
      'src/lib/taskDeletionManager.test.ts',
      'src/lib/taskSubmissionService.ts',
      'src/lib/taskSubmissionService.test.ts',
      'src/lib/legacyAgentActions.ts',
      'src/lib/legacyAgentExecution.ts',
      'src/lib/legacyAgentActions.test.ts',
      'src/lib/storeBootstrap.ts',
      'src/lib/storeBootstrap.test.ts',
      'src/lib/taskSelection.ts',
      'src/lib/taskSelection.test.ts',
      'src/lib/customProviderForm.ts',
      'src/lib/customProviderForm.test.ts',
      'src/lib/customProviderLlmPrompt.ts',
      'src/lib/contentEditableMentions.ts',
      'src/lib/settingsCopyUrl.ts',
      'src/lib/devProxyIntegration.test.ts',
      'src/components/planner/plannerHelpers.ts',
      'src/components/planner/plannerHelpers.test.ts',
      'src/components/planner/PlannerHistoryDrawer.tsx',
      'src/components/planner/PlannerHeader.tsx',
      'src/components/planner/PlannerReferenceImageGrid.tsx',
      'src/components/planner/PlannerInputPanel.tsx',
      'src/components/planner/useAmazonPlannerController.ts',
      'src/components/Select.tsx',
      'src/components/SearchBar.tsx',
      'src/components/AmazonPlanner.tsx',
      'src/components/SettingsModal.tsx',
      'src/components/settings/SettingsGeneralTab.tsx',
      'src/components/settings/SettingsAboutTab.tsx',
      'src/components/settings/SettingsDataTab.tsx',
      'src/components/settings/SettingsApiTab.tsx',
      'src/components/InputBar.tsx',
      'src/components/input/InputParameterPanel.tsx',
      'src/components/input/InputSubmitControls.tsx',
      'src/components/input/useSelectionDownload.ts',
      'src/components/input/inputBarParams.ts',
      'src/components/input/inputBarParams.test.ts',
      'src/components/planner/MarketplaceControls.tsx',
      'src/lib/amazonMarketplaces.ts',
      'src/lib/listingPlanner.ts',
      'src/lib/listingPlannerApi.ts',
      'src/lib/workspaceDrafts.ts',
      'src/lib/gallerySubmission.ts',
      'src/store.ts',
      'src/lib/aliyunQwenImageApi.ts',
      'src/lib/falAiImageApi.ts',
      'src/lib/volcengineImageApi.ts',
    ],
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },
)
